Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/BlockDelimiters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
